[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 1_000_000
fs_permissions = [
    { access = "readwrite", path = "./addresses" },
    { access = "read", path = "./package.json" },
    { access = "readwrite", path = "./deterministicConfig" },
    { access = "read", path = "../shared-contracts/chainConfigs" },
    { access = "read-write", path = "./circuits" },
    { access = "read-write", path = "/tmp/" },
]
ffi = true
evm_version = "london"
via_ir = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 150
quote_style = "double"
tab_width = 4

[rpc_endpoints]
